name: accflow

# num_frames controls input sequence length:
# - num_frames=2: pc0, pc1 only (no history)
# - num_frames=3: pc0, pc1, pch1 (1 history frame)
# - num_frames=5: pc0, pc1, pch1, pch2, pch3 (3 history frames)
# For inference: requires history frames + pc0 + pc1
# For accumulated training: also requires future frames pc2, pc3, ...

target:
  _target_: src.models.AccFlow
  voxel_size: ${voxel_size}
  point_cloud_range: ${point_cloud_range}
  num_frames: ${num_frames}
  planes: [16, 32, 64, 128, 256, 256, 128, 64, 32, 16]
  num_layer: [2, 2, 2, 2, 2, 2, 2, 2, 2]
  decay_factor: 0.4  # 自监督案例为啥用0.9? TeFlow 也是0.9? 不知道，试试吧。
  decoder_option: default  # choices: [default, deflow]
  knn_k: 1
  interpolation_method: knn_soft  # choices: [knn, three_nn, rbf, idw, knn_soft, rbf_soft]
  # Probability distribution for number of accumulation steps during training
  # [p1, p2, p3, p4] where pi = probability of accumulating i steps
  # Set to null for standard training without accumulated error
  accumulate_probs: ${target.accumulate_probs}

val_monitor: val/Dynamic/Mean
