name: accflow2frame

# Override global num_frames for this model - required for accumulated error training
num_frames: 5

target:
  _target_: src.models.AccFlow2Frame
  voxel_size: ${voxel_size}
  point_cloud_range: ${point_cloud_range}
  num_frames: ${num_frames}  # Number of frames in dataset for accumulation (still 5)
  planes: [16, 32, 64, 128, 256, 256, 128, 64, 32, 16]
  num_layer: [2, 2, 2, 2, 2, 2, 2, 2, 2]
  decay_factor: 0.4
  decoder_option: default  # choices: [default, deflow] - no time_aware needed
  knn_k: 3
  interpolation_method: knn
  # Probability distribution for number of accumulation steps during training
  accumulate_probs: [0.5, 0.25, 0.125, 0.125]

val_monitor: val/Dynamic/Mean
